### ISSUE TITLE
'berlin_hex' not found

### ISSUE THREAD

**Issue by nicolofp** [RamiKrispin/30DayMapChallenge#1]
Hello Rami,

This repository is amazing!
I was trying to reproduce your code but I cannot find the 'berlin_hex' object. 
I've never worked with maps and geo-data, am I missing any important detail?

Thank you
Nicolo'

**Comment by RamiKrispin** [comment]
Hi Nicolo'

I forgot to commit this part, just pushed it, see this [line](https://github.com/RamiKrispin/30DayMapChallenge/blob/1b625cccc3dbd5499a21405f2a9f167a07f6a582/day21/kontur_pop.R#L33).

Please let me know if you have any issues with recreating this plot.

Best,
Rami

**Comment by nicolofp** [comment]
Thank you! I was able to recreate it!

Best,
Nicolo'
